#!/usr/bin/env python3
"""Build include/data/large_airports.h from OurAirports (large_airport only)."""

from __future__ import annotations

import argparse
import csv
import io
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "include" / "data" / "large_airports.h"

AIRPORTS_URL = (
    "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/"
    "airports.csv"
)
RUNWAYS_URL = (
    "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/"
    "runways.csv"
)


def fetch_csv(url: str) -> list[dict[str, str]]:
    with urllib.request.urlopen(url, timeout=60) as resp:
        text = resp.read().decode("utf-8")
    return list(csv.DictReader(io.StringIO(text)))


def coord_e7(s: str | None) -> int | None:
    if not s or not s.strip():
        return None
    return int(round(float(s) * 1e7))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated header would change.",
    )
    args = parser.parse_args()

    airports = fetch_csv(AIRPORTS_URL)
    runways = fetch_csv(RUNWAYS_URL)

    large_idents: dict[str, tuple[int, int]] = {}
    for a in airports:
        if a.get("type") != "large_airport":
            continue
        ident = (a.get("ident") or "").strip()
        if len(ident) != 4:
            continue
        lat = coord_e7(a.get("latitude_deg"))
        lon = coord_e7(a.get("longitude_deg"))
        if lat is None or lon is None:
            continue
        large_idents[ident] = (lat, lon)

    best_runway: dict[str, dict[str, str]] = {}
    for r in runways:
        if r.get("closed") == "1":
            continue
        ident = (r.get("airport_ident") or "").strip()
        if ident not in large_idents:
            continue
        try:
            length_ft = int(r.get("length_ft") or 0)
        except ValueError:
            continue
        if length_ft <= 0:
            continue
        le_lat = coord_e7(r.get("le_latitude_deg"))
        le_lon = coord_e7(r.get("le_longitude_deg"))
        he_lat = coord_e7(r.get("he_latitude_deg"))
        he_lon = coord_e7(r.get("he_longitude_deg"))
        if None in (le_lat, le_lon, he_lat, he_lon):
            continue
        prev = best_runway.get(ident)
        if prev is None or length_ft > int(prev["length_ft"]):
            best_runway[ident] = r

    records: list[tuple[str, int, int, int, int, int, int, int, int]] = []
    for ident, (lat, lon) in sorted(large_idents.items()):
        r = best_runway.get(ident)
        if r is None:
            continue
        length_m = int(round(int(r["length_ft"]) * 0.3048))
        records.append(
            (
                ident,
                lat,
                lon,
                coord_e7(r["le_latitude_deg"]),  # type: ignore
                coord_e7(r["le_longitude_deg"]),  # type: ignore
                coord_e7(r["he_latitude_deg"]),  # type: ignore
                coord_e7(r["he_longitude_deg"]),  # type: ignore
                length_m,
            )
        )

    lines = [
        "// Generated by scripts/build_large_airports.py — do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace data::large_airports {",
        "",
        "struct Runway {",
        "  char ident[5];",
        "  int32_t lat_e7;",
        "  int32_t lon_e7;",
        "  int32_t le_lat_e7;",
        "  int32_t le_lon_e7;",
        "  int32_t he_lat_e7;",
        "  int32_t he_lon_e7;",
        "  uint16_t length_m;",
        "};",
        "",
        f"inline constexpr size_t kCount = {len(records)};",
        "",
        "inline constexpr Runway kRunways[] = {",
    ]
    for ident, lat, lon, le_lat, le_lon, he_lat, he_lon, length_m in records:
        lines.append(
            f'  {{"{ident}", {lat}, {lon}, {le_lat}, {le_lon}, '
            f"{he_lat}, {he_lon}, {length_m}}},"
        )
    lines += [
        "};",
        "",
        "}  // namespace data::large_airports",
        "",
    ]
    content = "\n".join(lines)

    if args.check:
        if not OUT.exists():
            print(f"missing {OUT}", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != content:
            print(f"stale {OUT} — run scripts/build_large_airports.py", file=sys.stderr)
            return 1
        print(f"ok ({len(records)} large airports)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT} ({len(records)} large airports)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
